name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
    - name: Install dependencies
      working-directory: ./My_TodoList/app
      run : |
        go version
        go get .
        go get -u github.com/dlgusrb3456/get_UUID
        go get -u github.com/gorilla/mux
        go get -u github.com/gorilla/sessions
        go get -u github.com/unrolled/render
        go get -u github.com/urfave/negroni
        go get -u go_WEB/My_TodoList/model
        go get -u golang.org/x/oauth2
        go get -u golang.org/x/oauth2/google
      env:
        GOPATH: /home/runner/work/Lackm/go

    - name: Test Go
      working-directory: ./My_TodoList/app
      run: go test -v
      env:
        GOPATH: /home/runner/work/Lackm/go